version: "3"
services:
  front:
    image: thecodingmachine/nodejs:14
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: $JITSI_URL
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: "$NODE_ENV"
      API_URL: pusher.workadventure.stuve-bamberg.de
      UPLOADER_URL: uploader.workadventure.stuve-bamberg.de
      ADMIN_URL: admin.workadventure.stuve-bamberg.de
      STARTUP_COMMAND_1: yarn install
      TURN_SERVER: "turn:coturn.workadventu.re:443,turns:coturn.workadventu.re:443"
      TURN_USER: workadventure
      TURN_PASSWORD: WorkAdventure123
    command: yarn run start
    volumes:
      - ./front:/usr/src/app
    networks:
      - frontend_net
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:play.workadventure.stuve-bamberg.de"
      - "traefik.docker.network=frontend_net"
      - "traefik.frontend.redirect.entryPoint=https"
#      - "traefik.http.routers.front.rule=Host(`play.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.front.entryPoints=web,traefik"
#      - "traefik.http.services.front.loadbalancer.server.port=8080"
#      - "traefik.http.routers.front-ssl.rule=Host(`play.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.front-ssl.entryPoints=websecure"
#      - "traefik.http.routers.front-ssl.tls=true"
#      - "traefik.http.routers.front-ssl.service=front"

  pusher:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run prod
    #command: yarn run profile
    environment:
      DEBUG: "*"
      STARTUP_COMMAND_1: yarn install
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      SECRET_KEY: yourSecretKey
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      API_URL: back:50051
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    volumes:
      - ./pusher:/usr/src/app
    networks:
      - frontend_net
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:pusher.workadventure.stuve-bamberg.de"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Headers:*||Access-Control-Allow-Origin:*"
      - "traefik.docker.network=frontend_net"
      - "traefik.frontend.redirect.entryPoint=https"

#      - "traefik.http.routers.pusher.rule=Host(`pusher.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.pusher.entryPoints=web"
#      - "traefik.http.services.pusher.loadbalancer.server.port=8080"
#      - "traefik.http.routers.pusher-ssl.rule=Host(`pusher.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.pusher-ssl.entryPoints=websecure"
#      - "traefik.http.routers.pusher-ssl.tls=true"
#      - "traefik.http.routers.pusher-ssl.service=pusher"

  maps:
    image: thecodingmachine/nodejs:12-apache
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: "$NODE_ENV"
      #APACHE_DOCUMENT_ROOT: dist/
      #APACHE_EXTENSIONS: headers
      #APACHE_EXTENSION_HEADERS: 1
      STARTUP_COMMAND_0: sudo a2enmod headers
      STARTUP_COMMAND_1: yarn install
      STARTUP_COMMAND_2: yarn run dev &
    volumes:
      - ./maps:/var/www/html
    networks:
      - frontend_net
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:maps.workadventure.stuve-bamberg.de"
      - "traefik.docker.network=frontend_net"
      - "traefik.frontend.redirect.entryPoint=https"

   #  - "traefik.http.routers.maps.rule=Host(`maps.workadventure.stuve-bamberg.de`)"
   #   - "traefik.http.routers.maps.entryPoints=web,traefik"
   #   - "traefik.http.services.maps.loadbalancer.server.port=80"
   #   - "traefik.http.routers.maps-ssl.rule=Host(`maps.workadventure.stuve-bamberg.de`)"
   #   - "traefik.http.routers.maps-ssl.entryPoints=websecure"
   #   - "traefik.http.routers.maps-ssl.tls=true"
   #   - "traefik.http.routers.maps-ssl.service=maps"

  back:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run profile
    environment:
      DEBUG: "*"
      STARTUP_COMMAND_1: yarn install
      SECRET_KEY: yourSecretKey
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ALLOW_ARTILLERY: "true"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    volumes:
      - ./back:/usr/src/app
    networks:
      - frontend_net
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.workadventure.stuve-bamberg.de"
      - "traefik.docker.network=frontend_net"
      - "traefik.frontend.redirect.entryPoint=https"

#      - "traefik.http.routers.back.rule=Host(`api.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.back.entryPoints=web"
#      - "traefik.http.services.back.loadbalancer.server.port=8080"
#      - "traefik.http.routers.back-ssl.rule=Host(`api.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.back-ssl.entryPoints=websecure"
#      - "traefik.http.routers.back-ssl.tls=true"
#      - "traefik.http.routers.back-ssl.service=back"

  uploader:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run profile
    environment:
      DEBUG: "*"
      STARTUP_COMMAND_1: yarn install
    volumes:
      - ./uploader:/usr/src/app
    networks:
      - frontend_net
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:uploader.workadventure.stuve-bamberg.de"
      - "traefik.docker.network=frontend_net"
      - "traefik.frontend.redirect.entryPoint=https"

#      - "traefik.http.routers.uploader.rule=Host(`uploader.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.uploader.entryPoints=web"
#      - "traefik.http.services.uploader.loadbalancer.server.port=8080"
#      - "traefik.http.routers.uploader-ssl.rule=Host(`uploader.workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.uploader-ssl.entryPoints=websecure"
#      - "traefik.http.routers.uploader-ssl.tls=true"
#      - "traefik.http.routers.uploader-ssl.service=uploader"

  website:
    image: thecodingmachine/nodejs:12-apache
    environment:
      STARTUP_COMMAND_1: npm install
      STARTUP_COMMAND_2: npm run watch &
      APACHE_DOCUMENT_ROOT: dist/
    volumes:
      - ./website:/var/www/html
    networks:
      - frontend_net
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:workadventure.stuve-bamberg.de"
      - "traefik.docker.network=frontend_net"
      - "traefik.frontend.redirect.entryPoint=https"

#      - "traefik.http.routers.website.rule=Host(`workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.website.entryPoints=web"
#      - "traefik.http.services.website.loadbalancer.server.port=80"
#      - "traefik.http.routers.website-ssl.rule=Host(`workadventure.stuve-bamberg.de`)"
#      - "traefik.http.routers.website-ssl.entryPoints=websecure"
#      - "traefik.http.routers.website-ssl.tls=true"
#      - "traefik.http.routers.website-ssl.service=website"

  messages:
    #image: thecodingmachine/nodejs:14
    image: thecodingmachine/workadventure-back-base:latest
    environment:
      #STARTUP_COMMAND_0: sudo apt-get install -y inotify-tools
      STARTUP_COMMAND_1: yarn install
      STARTUP_COMMAND_2: yarn run proto:watch
    volumes:
      - ./messages:/usr/src/app
      - ./back:/usr/src/back
      - ./front:/usr/src/front
      - ./pusher:/usr/src/pusher

networks:
  frontend_net:
    external: true

